### ISSUE TITLE
Case control for Auto complete

### ISSUE THREAD

**Issue by mykael22000** [BroadcomMFD/rexx-language-support#13]
This is Rexx, not EXEC2.  Rexx lets me write my keywords in mixed case, not SHOUT THEM IN UPPER CASE.

Problem is that even if I type the keyword in in Mixed case, Auto complete is then changing it into ugly upper case.  

A good example is:

`If var = 1 Then`

When I hit enter after the Then, auto complete is turning my line into:

`If var = 1 THEN`

...which isn't what I want.

Any chance of getting mixed case support for it? Or, at the least, for it to leave things I've typed in alone...

**Comment by niharikasw91** [comment]
@mykael22000 ,Thank you for the feedback.
We are working on improvement and will share the progress with you.

**Comment by zimlu02** [comment]
Hi @mykael22000,
thank you for your feedback. We are working on addressing your issue. 
Please, if you want, reach out to me on my email - lukas.zima@broadcom.com.
We would be interested in your use cases or other ideas and wishes.
Thank you.

**Comment by zimlu02** [comment]
Solved in the latest release:
https://github.com/BroadcomMFD/rexx-language-support/releases/tag/0.0.18
Closing the issue.
