### ISSUE TITLE
Unble to execute rexx by using Broadcom Rexx Plugin

### ISSUE THREAD

**Issue by Anant-Shandilyan** [BroadcomMFD/rexx-language-support#16]
Hi, 
 I have installed Rexx Plugin and Running Rexx in Plugin but while doing "Run" command nothing is coming out. Its saying there is no Rexx plugin. Can anyone please help me! Thanks alot!

![image](https://github.com/BroadcomMFD/rexx-language-support/assets/102076043/1a726bb6-35ab-437d-b6c3-569adf3221fd)

Best regards,
Anant

**Comment by ishche** [comment]
Hello!
Thank you for trying our extension. As for now, we don't support launch configuration.
As a workaround, you can consider tasks in vscode: https://code.visualstudio.com/docs/editor/tasks
Also this post can be useful: https://dkelosky.medium.com/running-z-os-rexx-from-persistent-tso-address-space-w-zowe-cli-800386228085

**Comment by zimlu02** [comment]
Hello Anant,
please let me close this issue as we don't plan to support this feature.
