### ISSUE TITLE
Lower case

### ISSUE THREAD

**Issue by COBOL-Erik** [BroadcomMFD/rexx-language-support#7]
I would like the autocompleted Rexx in lower case letters.

**Comment by ishche** [comment]
Will it make sense if your word start in lower case then the suggested keyword is in the lower case also?

**Comment by COBOL-Erik** [comment]
That would be perfect!

**Comment by ishche** [comment]
There is a 0.0.16 version available on the marketplace.
Can you please give it a try?

**Comment by ishche** [comment]
Hello! I make some changes to autocomplete logic. Can you please check it out, if it works for you? Version 0.0.17 is available on the marketplace to update.

**Comment by COBOL-Erik** [comment]
Seems to work! Thank you!
